<a href="https://colab.research.google.com/github/strejo4/ColabFiles_UACJ_PADP/blob/main/Factorizacion_de_matrices_Tarea_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Obtenga la factorización LU de la matriz B

In [2]:
import numpy as np
# Importamos la función lu de SciPy, que hace la factorización LU
from scipy.linalg import lu
# Esta es la matriz que se construyo para que fuera diagonalmente dominante
B = np.array([[9.75, 4.5, -2],
              [-1, -2, 4.5],
              [-2, 4.5, -1]])

# Aplicamos la factorización LU sobre B
# SciPy devuelve tres matrices: P, L y U
P, L, U = lu(B)

# Imprimimos la matriz de permutación P
# P indica si se intercambiaron filas durante la factorización
print("P =\n", P)

# Imprimimos la matriz L
print("L =\n", L)

# Imprimimos la matriz U
print("U =\n", U)

# Verificación:
# Multiplicamos P * L * U y mostramos el resultado
# Debe ser exactamente igual a la matriz original B
print("P·L·U =\n", P @ L @ U)



P =
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
L =
 [[ 1.          0.          0.        ]
 [-0.20512821  1.          0.        ]
 [-0.1025641  -0.28368794  1.        ]]
U =
 [[ 9.75        4.5        -2.        ]
 [ 0.          5.42307692 -1.41025641]
 [ 0.          0.          3.89479905]]
P·L·U =
 [[ 9.75  4.5  -2.  ]
 [-1.   -2.    4.5 ]
 [-2.    4.5  -1.  ]]
