<a href="https://colab.research.google.com/github/strejo4/ColabFiles_UACJ_PADP/blob/main/Practica4_SergioTrejo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulación de matrices

**Crea dos matrices de 3x3 con números aleatorios entre 1 y 10. Realiza las siguientes operaciones:**

* Suma ambas matrices.
* Resta la segunda matriz de la primera.
* Multiplica la primera matriz por 2.
* Realiza una multiplicación matricial entre las dos matrices.

In [9]:
import numpy as np

A = np.random.randint(1, 11, (3, 3))
B = np.random.randint(1, 11, (3, 3))

print(f'Matriz A: {A}')
print(f'Matriz B:{B}')

#Suma de ambas matrices
suma_matrices = A + B
print(f'Suma de ambas matrices: {suma_matrices}')

#Resta la segunda matrix de la primera
resta_matrices = A - B
print(f'Resta de ambas matrices: {resta_matrices}')

#Multiplica la primera matriz por 2
multiplicacion_matrices = A * 2
print(f'Multiplicacion de ambas matrices: {multiplicacion_matrices}')

#Realiza una multiplicacion matricial entre las dos matrices
multiplicacion_matricial = np.dot(A, B)
print(f'Multiplicacion matricial de ambas matrices: {multiplicacion_matricial}')

Matriz A: [[ 5  3  3]
 [ 3  7  1]
 [ 3  5 10]]
Matriz B:[[ 1  1  7]
 [10  9  7]
 [ 9  5 10]]
Suma de ambas matrices: [[ 6  4 10]
 [13 16  8]
 [12 10 20]]
Resta de ambas matrices: [[ 4  2 -4]
 [-7 -2 -6]
 [-6  0  0]]
Multiplicacion de ambas matrices: [[10  6  6]
 [ 6 14  2]
 [ 6 10 20]]
Multiplicacion matricial de ambas matrices: [[ 62  47  86]
 [ 82  71  80]
 [143  98 156]]
